### ISSUE TITLE
Build error: Undeclared function 'AtomicIncrement'

### ISSUE THREAD

**Issue by mazinsw** [synopse/SynPDF#1]
![error](https://cloud.githubusercontent.com/assets/7927014/7442722/05a231e8-f0f3-11e4-8756-d9d1f72b848c.png)

[DCC Error] SynCommons.pas(17276): E2003 Undeclared identifier: 'AtomicIncrement'
[DCC Error] SynCommons.pas(17281): E2003 Undeclared identifier: 'AtomicDecrement'
[DCC Fatal Error] SynPDFDXE2.dpk(36): F2063 Could not compile used unit 'SynCommons.pas'

How to reproduce:
Try build with Delphi XE2 Update 4 HostFix 1, Build Configuration: Release or Debug, Target Plataforms: Win64 on Windows 7 64 bits Professional.

How to solve:
Replace: Line 17276
  result := AtomicIncrement(I);
By
  Result := Windows.InterlockedIncrement(I);

Replace: Line 17281
  result := AtomicDecrement(I);
By
  Result := Windows.InterlockedDecrement(I);

**Comment by synopse** [comment]
Fixed by https://github.com/synopse/SynPDF/commit/88921b027a603cb6ed566d0c17bb97994eaa60a4

Thanks for the report!
