### ISSUE TITLE
Privileged instruction Error

### ISSUE THREAD

**Issue by zekiguven** [synopse/SynPDF#10]
Hi,
Some computers raises "Privileged instruction" exception. 
It occurs in versions with updates.
gdi32.dll file is updated. 
gdi32.dll Version :10.0.14393.0 
gdi32.dll file size is 201K.

madExcept  log:
> 
> date/time         : 2016-09-02, 18:49:15, 600ms
> computer name     : ZAKIB
> user name         : ZakiT
> registered owner  : Hp
> operating system  : Windows 8 x64 build 9200
> system language   : Turkish
> system up time    : 2 days 9 hours
> program up time   : 1 minute 3 seconds
> processors        : 4x Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
> physical memory   : 9541/16265 MB (free/total)
> free disk space   : (C:) 270,16 GB
> display mode      : 1920x1080, 32 bit
> process id        : $2858
> allocated memory  : 202,01 MB
> command line      : "C:\Program Files (x86)\xxxxx\REPENGINE.EXE" 
> executable        : REPENGINE.EXE
> exec. date/time   : 2016-09-01 23:06
> version           : 1.0.0.2
> compiled with     : Delphi XE3
> madExcept version : 4.0.7
> callstack crc     : $75df162a, $e8b949c2, $7bcf8464
> exception number  : 1
> exception class   : EPrivilege
> exception message : Privileged instruction.
> 
> main thread ($3514):
> 75df162a +0000 GDI32.dll
> 0112ecf4 +009c REPENGINE.EXE SynPdf                   TPdfWrite.AddUnicodeHexTextUniScribe
> 0112f560 +0060 REPENGINE.EXE SynPdf                   TPdfWrite.AddUnicodeHexText
> 0113718b +002b REPENGINE.EXE SynPdf                   TPdfCanvas.ShowText
> 01135a04 +0058 REPENGINE.EXE SynPdf                   TPdfCanvas.TextOutW
> 0188b2a1 +0115 REPENGINE.EXE ReportDlg      1557  +16 TReportForm.TStartBtnClick
> 006261cb +006f REPENGINE.EXE Vcl.Controls             TControl.Click
> 005d10e2 +001e REPENGINE.EXE Vcl.StdCtrls             TCustomButton.Click
> 007987c1 +00a5 REPENGINE.EXE Vcl.Buttons              TBitBtn.Click
> 005d1c04 +0010 REPENGINE.EXE Vcl.StdCtrls             TCustomButton.CNCommand
> 00625c75 +02bd REPENGINE.EXE Vcl.Controls             TControl.WndProc
> 0062a709 +05c5 REPENGINE.EXE Vcl.Controls             TWinControl.WndProc
> 005d0d8c +006c REPENGINE.EXE Vcl.StdCtrls             TButtonControl.WndProc
> 006258b0 +0024 REPENGINE.EXE Vcl.Controls             TControl.Perform
> 0062a86f +0023 REPENGINE.EXE Vcl.Controls             DoControlMsg
> 0062b2f7 +000b REPENGINE.EXE Vcl.Controls             TWinControl.WMCommand
> 00625c75 +02bd REPENGINE.EXE Vcl.Controls             TControl.WndProc
> 0062a709 +05c5 REPENGINE.EXE Vcl.Controls             TWinControl.WndProc
> 00656c0e +007a REPENGINE.EXE Vcl.Themes               TStyleHook.WndProc
> 00629d4c +002c REPENGINE.EXE Vcl.Controls             TWinControl.MainWndProc
> 004dc3cc +0014 REPENGINE.EXE System.Classes           StdWndProc
> 77b0fef4 +0034 ntdll.dll                             KiUserCallbackDispatcher
> 77340bcb +013b USER32.dll                            SendMessageW
> 005db7d3 +0043 REPENGINE.EXE Vcl.StdCtrls             TButtonStyleHook.DoClick
> 005dbb4b +002b REPENGINE.EXE Vcl.StdCtrls             TButtonStyleHook.WMLButtonUp
> 00656c0e +007a REPENGINE.EXE Vcl.Themes               TStyleHook.WndProc
> 00656dfc +0000 REPENGINE.EXE Vcl.Themes               TMouseTrackControlStyleHook.WndProc
> 005db874 +005c REPENGINE.EXE Vcl.StdCtrls             TButtonStyleHook.WndProc
> 00656594 +0064 REPENGINE.EXE Vcl.Themes               TStyleHook.HandleMessage
> 006ba966 +0116 REPENGINE.EXE Vcl.Styles               TStyleEngine.HandleMessage
> 006539ac +0054 REPENGINE.EXE Vcl.Themes               TStyleManager.HandleMessage
> 00628a93 +000f REPENGINE.EXE Vcl.Controls             TWinControl.DoHandleStyleMessage
> 0062a19f +005b REPENGINE.EXE Vcl.Controls             TWinControl.WndProc
> 005d0d8c +006c REPENGINE.EXE Vcl.StdCtrls             TButtonControl.WndProc
> 00629d4c +002c REPENGINE.EXE Vcl.Controls             TWinControl.MainWndProc
> 004dc3cc +0014 REPENGINE.EXE System.Classes           StdWndProc
> 005f585b +00f3 REPENGINE.EXE Vcl.Forms                TApplication.ProcessMessage
> 005f589e +000a REPENGINE.EXE Vcl.Forms                TApplication.HandleMessage
> 005f5bd9 +00c9 REPENGINE.EXE Vcl.Forms                TApplication.Run
> 04598060 +0468 REPENGINE.EXE REPENGINE                 initialization
> 76b962c2 +0022 KERNEL32.DLL                          BaseThreadInitThunk
> 
> thread $302c:
> 76452af4 +84 KERNELBASE.dll  SleepEx
> 76452a5a +0a KERNELBASE.dll  Sleep
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3cd4:
> 76452af4 +84 KERNELBASE.dll  SleepEx
> 76452a5a +0a KERNELBASE.dll  Sleep
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $2634:
> 76452af4 +84 KERNELBASE.dll  SleepEx
> 76452a5a +0a KERNELBASE.dll  Sleep
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $31c0:
> 76452af4 +84 KERNELBASE.dll  SleepEx
> 76452a5a +0a KERNELBASE.dll  Sleep
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $254c:
> 76452af4 +84 KERNELBASE.dll  SleepEx
> 76452a5a +0a KERNELBASE.dll  Sleep
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3b68:
> 76452af4 +84 KERNELBASE.dll  SleepEx
> 76452a5a +0a KERNELBASE.dll  Sleep
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $1c88:
> 76452af4 +84 KERNELBASE.dll  SleepEx
> 76452a5a +0a KERNELBASE.dll  Sleep
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $23c0:
> 76452af4 +84 KERNELBASE.dll  SleepEx
> 76452a5a +0a KERNELBASE.dll  Sleep
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $2b20:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3b8c:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $1ecc:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3194:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3ee0:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3590:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3c94:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $320c:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $1d9c:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $2c5c:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $35d0:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3c98:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3c08:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $16a8:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $1c38:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $1ea4:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $2388:
> 76452af4 +84 KERNELBASE.dll  SleepEx
> 76452a5a +0a KERNELBASE.dll  Sleep
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3888:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $371c:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $3998: <priority:2>
> 7735249d +4d USER32.dll                      GetMessageA
> 009b5385 +0d REPENGINE.EXE madExcept 16670 +6 CallThreadProcSafe
> 009b53ea +32 REPENGINE.EXE madExcept 16720 +9 ThreadExceptFrame
> 76b962c2 +22 KERNEL32.DLL                    BaseThreadInitThunk
> >> created by main thread ($3514) at:
> 70b830ab +00 winmm.dll
> 
> thread $3024:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $3dd8:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $3cf4:
> 76451a2a +ea KERNELBASE.dll                    WaitForMultipleObjectsEx
> 009b5385 +0d REPENGINE.EXE   madExcept 16670 +6 CallThreadProcSafe
> 009b53ea +32 REPENGINE.EXE   madExcept 16720 +9 ThreadExceptFrame
> 76b962c2 +22 KERNEL32.DLL                      BaseThreadInitThunk
> >> created by main thread ($3514) at:
> 7687d227 +00 combase.dll
> 
> thread $2364:
> 76451a2a +ea KERNELBASE.dll  WaitForMultipleObjectsEx
> 77348ea3 +63 USER32.dll      MsgWaitForMultipleObjects
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $b38:
> 76451a2a +ea KERNELBASE.dll  WaitForMultipleObjectsEx
> 77348ea3 +63 USER32.dll      MsgWaitForMultipleObjects
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3d68:
> 76451a2a +ea KERNELBASE.dll  WaitForMultipleObjectsEx
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $28ac:
> 76451a2a +ea KERNELBASE.dll  WaitForMultipleObjectsEx
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $3f14: <priority:2>
> 76451a2a +ea KERNELBASE.dll  WaitForMultipleObjectsEx
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $2b90:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $29c4:
> 7644ac83 +93 KERNELBASE.dll  WaitForSingleObjectEx
> 7644abdd +0d KERNELBASE.dll  WaitForSingleObject
> 76b962c2 +22 KERNEL32.DLL    BaseThreadInitThunk
> 
> thread $2500:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $1e8c:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $25d8:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $2964:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $2574:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $2598:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $25d4:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $1e4:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $3d3c:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $2ac8:
> 76451a69 +129 KERNELBASE.dll                    WaitForMultipleObjectsEx
> 77348941 +171 USER32.dll                        MsgWaitForMultipleObjectsEx
> 7690eac9 +089 combase.dll                       CoWaitForMultipleHandles
> 009b5385 +00d REPENGINE.EXE   madExcept 16670 +6 CallThreadProcSafe
> 009b53ea +032 REPENGINE.EXE   madExcept 16720 +9 ThreadExceptFrame
> 76b962c2 +022 KERNEL32.DLL                      BaseThreadInitThunk
> >> created by thread $371c at:
> 7616a62c +000 shcore.dll
> 
> thread $2494:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $29a4:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> thread $3728:
> 76b962c2 +22 KERNEL32.DLL  BaseThreadInitThunk
> 
> cpu registers:
> eax = 0019e346
> ebx = 01102d28
> ecx = 00000000
> edx = 01102dc4
> esi = 5574f164
> edi = 0019e428
> eip = 75df162a
> esp = 0019e320
> ebp = 0019e39c
> 
> stack dump:
> 0019e320  f9 ec 12 01 00 00 00 00 - 46 e3 19 00 44 e3 19 00  ........F...D...
> 0019e330  fc e3 19 00 40 b5 40 00 - 9c e3 19 00 00 00 00 00  ....@.@.........
> 0019e340  2c 0f 45 76 00 00 00 00 - 00 00 6f 27 00 00 00 00  ,.Ev......o'....
> 0019e350  00 00 00 00 14 e4 19 00 - e6 04 00 00 00 00 00 00  ................
> 0019e360  00 00 00 00 00 00 00 00 - 02 00 00 00 40 a0 8f 00  ............@...
> 0019e370  01 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ................
> 0019e380  04 00 00 00 24 54 86 20 - 00 00 00 00 10 9f d7 24  ....$T. .......$
> 0019e390  10 ad 86 1e f4 fe 6f 27 - 01 00 00 00 c4 e3 19 00  ......o'........
> 0019e3a0  65 f5 12 01 20 8d 89 1e - 00 9c 21 16 00 ee df 16  e... .....!.....
> 0019e3b0  10 9f d7 24 03 00 00 00 - 04 00 00 00 24 54 86 20  ...$........$T.
> 0019e3c0  10 ad 86 1e dc e3 19 00 - 90 71 13 01 20 8d 89 1e  .........q.. ...
> 0019e3d0  10 ad 86 00 24 54 86 20 - 20 8d 89 1e ec e3 19 00  ....$T.  .......
> 0019e3e0  09 5a 13 01 24 54 86 20 - 20 8d 89 1e 48 e4 19 00  .Z..$T.  ...H...
> 0019e3f0  ed e6 8f 01 cd 2c 4a 44 - 00 00 03 44 54 e4 19 00  .....,JD...DT...
> 0019e400  40 b5 40 00 48 e4 19 00 - 80 e4 19 00 18 e5 19 00  @.@.H...........
> 0019e410  00 00 00 00 00 00 00 00 - 0c 02 00 00 1b 00 00 00  ................
> 0019e420  13 02 00 00 27 00 00 00 - 30 a7 b2 00 44 e4 19 00  ....'...0...D...
> 0019e430  00 00 00 00 6c e4 19 00 - 0c 02 00 00 02 00 00 00  ....l...........
> 0019e440  14 55 86 20 f0 22 8e 1e - 88 e4 19 00 32 05 90 01  .U. ."......2...
> 0019e450  00 00 00 00 9c e4 19 00 - 40 b5 40 00 88 e4 19 00  ........@.@.....

**Comment by synopse** [comment]
See discussion in http://synopse.info/forum/viewtopic.php?pid=21641#p21641

Sounds like a multi-threading issue in your code - unless you can provide some small code sample (in pastebin) to reproduce it.
