### ISSUE TITLE
protected PDFs shows garbage in document information (e.G. Adobe Reader)

### ISSUE THREAD

**Issue by kalwados** [synopse/SynPDF#32]
When the PDF document uses encryption to ensure no modifications, the resulting PDF files contains some kind of garbage in the document properties; see Screenshot.

Example:
```Delphi
LPdf := TPdfDocumentGDI.Create(
  false, 0 , false, 
  TPDFEncryption.New(elRC4_40, '', 'secret', [epPrinting])
);
LPdf.Info.Author := 'User name';
LPdf.Info.Creator := 'Software name';
LPdf.Info.Subject = 'Auto generated document';
```
![SynPDF document properties](https://user-images.githubusercontent.com/11840444/72525782-3d542b00-3865-11ea-9632-ac5234fafef0.png)

**Comment by synopse** [comment]
Seems to be confirmed as fixed. ;)
