### ISSUE TITLE
Update/Change the default FontFallBackName

### ISSUE THREAD

**Issue by Daniel-Tr** [synopse/SynPDF#37]
The default value for the FontFallBackName is set to "Arial Unicode MS". This font type is no longer maintained by Microsoft and no longer included with Office at is has been. Microsoft sells the font at 209€ per license instead, which doesn't make it a good default value.

I would propose 'Noto Sans CJK JP Regular' as a new default value, as it is freely available and supports a similar range of characters. It's an OpenType font though and not yet supported.

**Comment by synopse** [comment]
... but only for JP glyphs I guess ;)
I will add a reference to Noto fonts to the unit comments
