### ISSUE TITLE
Access Violation on Delphi 10.4.1 with byte record field alignment

### ISSUE THREAD

**Issue by ttyrakow** [synopse/SynPDF#40]
Generating a PDF via VLCCanvas and TPdfDocumentGDI causes access violation when compiled with Delphi 10.4.1 with record field alignment compiler option set to "byte" or "off". When this option is set to either of "word", "double word" or "quad word", the PDF gets created without errors. The same exact code works fine when compiled with Delphi 10.4 (patch 3), regardless of the field alignment flag.
It smells like an off-by-one error somewhere (that's why introducing gaps between record fields circumvents it), but I wasn't able to pinpoint it. The exception appears in TPdfWrite.Save method, where the L variable seems to be assigned a meaningless value (zero or negative). But since there's a lot of pointer math and memory copying, the actual cause might as well be completely elsewhere.
Minimal example I managed to put together, which reproduces the error:
```
procedure TForm1.testButtonClick(Sender: TObject);
var
  outfile: TFileStream;
  pdfdoc: TPdfDocumentGDI;
begin

  if FileExists('test.pdf') then
    DeleteFile('test.pdf');
  outfile := TFileStream.Create('test.pdf', fmCreate);
  try
    pdfdoc := TPdfDocumentGDI.Create();
    try
      pdfdoc.GeneratePDF15File := true;
      pdfdoc.SaveToStreamDirectBegin(outfile);
      pdfdoc.AddPage();
      pdfdoc.VCLCanvas.TextOut(20, 20, 'ABC');
      pdfdoc.SaveToStreamDirectPageFlush();
      pdfdoc.SaveToStreamDirectEnd();
    finally
      pdfdoc.Free();
    end;
  finally
    outfile.Free();
  end;
end;
```
When compiled on 10.4.1 with byte aligned records it crashes, with word (or wider) alignment it works fine. Compiled on D10.4 works well in all cases. All other compiler options except the field alignment was set to IDE default.
Currently I have access to active installations of both D10.4 and D10.4.1, so if I could assist in some testing, I'd be happy to do so (those are corporate machines, so I can't provide any kind of remote access, but I can compile and run test projects and let you know what happens).
The zipped project in the comments below.

**Comment by ttyrakow** [comment]
[synpdftest.zip](https://github.com/synopse/SynPDF/files/5187459/synpdftest.zip)

**Comment by synopse** [comment]
I don't have access to Delphi 10.4.1 since I don't have any commercial licence, and I am waiting for the Community Edition - which is still 10.3 IIRC.
So you don't suffer from this issue with 10.3?
Try to add a {$A+} at the beginning of SynPDF.

**Comment by ttyrakow** [comment]
With {$A+} at the beginning of SynPdf.pas there is no crash (but it's just the local version of the project option I mentioned above, nevertheless I'm happy it does the trick, because a global change in field alignment impacts other code as well). And the problem started to appear after I upgraded from 10.4 to 10.4.1. In 10.4, regardless of patch level (I used it without patch and then in all patches 1-3 in turn), there were no crashes. So it worked in 10.3 and 10.4 and stopped working in 10.4.1.
Something must have changed between 10.4 and 10.4.1, which affects SynPDF in a subtle way, but I couldn't find anything relevant in the Delphi changelog (which is laconic to say the least).

**Comment by synopse** [comment]
It is indeed likely to be a default alignment problem with records.

Perhaps I will add the explicit {$A+} in the Synopse.inc include file, for all units, since the framework code expects this default alignment everywhere, and switch to "packed" or {$A1} when needed - and fallback to {$A+} afterwards.
What do you think?

**Comment by ttyrakow** [comment]
That seems a good idea for now. However, it's just a workaround, the real cause is there somewhere, but of course I realize that without access to D10.4.1 it would be next to impossible for you to find it. On the other hand, I lack the knowledge of SynPDF internals to find the solution myself in acceptable time (and I have to admit I don't like pointer arithmetic and avoid it whenever I can - it's too easy to do it the wrong way).
So maybe add $A+ and let's call it a day for now.
Thank you for a prompt reply and I hope Embarcadero will release D10.4.1 CE soon.

**Comment by fpiette** [comment]
I have posted answers in [https://en.delphipraxis.net/topic/3453-record-alignement-and-delphi-1041/](DelphiPraxis) where you posted your message. Please have a look at my analysis.
