### ISSUE TITLE
Delphi 7 compile error SetFont

### ISSUE THREAD

**Issue by Jozkzk** [synopse/SynPDF#41]
I just downloaded the source code and when I compile I get that error
[Error] QRPDFSynFilt.pas(1082): There is no overloaded version of 'SetFont' that can be called with these arguments.

**Comment by synopse** [comment]
This is a problem of your QuickReport filter unit I guess, not a mORMot issue.

**Comment by Jozkzk** [comment]
Thanks for the awnser.
I would put more information here.
Today I updated my QR to the last D7 verison (5.02.2)
Everything was fine, but I got an AV error exporting to PDF
So I  just updated the SynPDF files to the latest version and now I have that error in QRPDFSynFilt line 1082

      pdfdoc.Canvas.SetFont(itemobj.itemrec.FontName, itemobj.itemrec.FontSize, textstyle);

**Comment by synopse** [comment]
So the QRPDFSynFilt.pas unit is to be adapted to follow SynPDF.
We don't maintain QRPDFSynFilt and are not able to since we don't use it.

**Comment by Jozkzk** [comment]
Im sorry, only now I realized QRPDFSynFilt is not part of SynPDF
