### ISSUE TITLE
Comparing signed and unsigned types - widened both operands in delphi Sidney

### ISSUE THREAD

**Issue by automacaosamos** [synopse/SynPDF#44]
[dcc32 Error] SynCrypto.pas(6661): E2034 Too many actual parameters
[dcc32 Error] SynCrypto.pas(6668): E2034 Too many actual parameters
[dcc32 Error] SynCrypto.pas(14624): E2003 Undeclared identifier: 'Hash128Index'
[dcc32 Warning] SynCrypto.pas(14624): W1023 Comparing signed and unsigned types - widened both operands
[dcc32 Error] SynCrypto.pas(14630): E2003 Undeclared identifier: 'Hash128Index'
[dcc32 Warning] SynCrypto.pas(14630): W1023 Comparing signed and unsigned types - widened both operands
[dcc32 Fatal Error] SynPdf.pas(927): F2063 Could not compile used unit 'SynCrypto.pas'
Failed

**Comment by synopse** [comment]
Not able to reproduce.
