### ISSUE TITLE
Warning for ESynException.CreateLastOSError

### ISSUE THREAD

**Issue by gonutz** [synopse/SynPDF#45]
On Delphi XE 4 I get this warning

    [dcc32 Warning] W1029 Duplicate constructor 'ESynException.CreateLastOSError' with identical parameters will be inacessible from C++

which I fixed by changing `ESynException.CreateLastOSError` from this

    constructor CreateLastOSError(const Format: RawUTF8; const Args: array of const);

to this

    // Note that the Unused parameter is just there to shut up warnings that this
    // constructor is identical in paramaters to the above CreateUTF8 and can thus not be
    // used in C++.
    constructor CreateLastOSError(const Format: RawUTF8; const Args: array of const; Unused: Integer = 0);

Adding the `Unused` parameter with a default value keeps the code intact and shuts up the warning.

**Comment by synopse** [comment]
Adding dummy/unused arguments works but is not very elegant.
The proper way of getting rid of this warning is to add in your project:
  {$warn DUPLICATE_CTOR_DTOR OFF} // avoid W1029 unneeded hints

So just include {$I Synopse.inc} in your .dpr.
It contains this directive.

**Comment by gonutz** [comment]
I see, thanks for pointing me at this :-)
