### ISSUE TITLE
Double/Wrong xref section

### ISSUE THREAD

**Issue by maykon-t** [synopse/SynPDF#48]
Hi,

I'm trying to debug a problem that occurs intermittently. I'm using the TPdfDocumentGDI class.
Often PDFs are not opened by some PDF readers, in particular Acrobat and the Firefox built-in reader. For Acrobat, the error returned is 109 (damaged file).
Other PDF readers seems to display the file without problems, like FoxIt and Google Chrome built-in reader.

After a comparative study between the generated files, I realized these problematic files have two sections startxref/xref/trailer at the end of the file, while in normal files there is only one section of each. I also noticed that the first xref section lists objects at wrong offsets and the second xref section seems to have consistent references.

Unfortunately, just my users got this problem until now and I wasn't successful trying to recreate it.

An example file containing the problem is attached.
[Example.pdf](https://github.com/synopse/SynPDF/files/6549616/Example.pdf)
Note the first xref section:

xref
0 12
0000000000 65535 f
0000000009 00000 n
0000000093 00000 n
0000000322 00000 n
0000000373 00000 n
0000000544 00000 n
0000005284 00000 n
0000005931 00000 n
0000006109 00000 n
0000006784 00000 n
0000006956 00000 n
0000007612 00000 n

From the seventh object, the offsets indicated are inconsistent with real objects in file. It is also important to note that the last xref section looks consistent.

Any idea what might be going on? Where can I start to debug this?

**Comment by synopse** [comment]
It sounds like if the second xref is in fact the remaining of a previous pdf generation.
If you cut down the pdf content to the first xref / %EOF line, then the pdf loads with no problem.

I guess the way the file is created is not correct.
Perhaps a TMemoryStream is reused, and not truncated.
