### ISSUE TITLE
SynPDF does not compile

### ISSUE THREAD

**Issue by dirk-qualisys** [synopse/SynPDF#49]
Under Delphi XE7 (and as I see it in every version), the code I downloaded on 27 May 2021 does not compile:

SynPDF.pas lines 5810-5812:

```
  with fMissingBookmarks do
  for i := Count-1 downto 0 do
    if Get(i)=aBookmarkName then begin
```
throws an error because the symbol Get is not defined. Looking at SynCommons.pas, TRawUTF8List has a `function Get(Index: PtrInt): RawUTF8; {$ifdef HASINLINE}inline;{$endif}` which is defined as `protected` .

I hope you can reproduce this. Possible solution: Make it public. I'll leave this decision to those who have more insight into structure and other applications of the library.

**Comment by synopse** [comment]
Your version of SynPdf seems outdated.

Current code is `if Strings[i]=aBookmarkName then begin` and compiles with no problem.

**Comment by dirk-qualisys** [comment]
Yes, today's download compiles. Thanks!
