### ISSUE TITLE
TAESCFB.SimpleEncrypt doesn't work for large files

### ISSUE THREAD

**Issue by xelnaga64** [synopse/SynPDF#50]
I use this code for file encryption:

```
var
  inputfile : RawByteString;
  outputfile: RawByteString;
begin
  inputfile := StringFromFile('c:\test1.mp4');
  outputfile := TAESCFB.SimpleEncrypt(inputfile,'TEST',true,true);
  FileFromString(outputfile,'c:\test2.mp4');
end;
```

However it doesn't work for large files (>1GB). Is there any way to encrypt large files?

**Comment by synopse** [comment]
This has nothing to do with SynPDF.

Please use https://synopse.info/forum for such questions.

TL&DR: there is no stream encryption support yet, only in-memory encryption.
