### ISSUE TITLE
Delphi 10.5 Olympus

### ISSUE THREAD

**Issue by koxo** [synopse/SynPDF#51]
Hi,
I'm trying the beta test version of Delphi 10.5 Olympus.
There is a problem with "**SynCommons.pas**".
The System.Classes TMempryStream has been modify : 
```
{ TMemoryStream }
  TMemoryStream = class(TCustomMemoryStream)
  private
    FCapacity: NativeInt;
  protected
    procedure SetCapacity(NewCapacity: NativeInt); virtual;
    function Realloc(var NewCapacity: NativeInt): Pointer; virtual;
    property Capacity: NativeInt read FCapacity write SetCapacity;
  public
    destructor Destroy; override;
    procedure Clear;
    procedure LoadFromStream(Stream: TStream);
    procedure LoadFromFile(const FileName: string);
    procedure SetSize(const NewSize: Int64); override;
    procedure SetSize(NewSize: Longint); override;
    function Write(const Buffer; Count: Longint): Longint; override;
  end;

```

Realloc Function must be modify too (LongInt --> NativeInt) : 

function THeapMemoryStream.Realloc(var NewCapacity: **NativeInt**): Pointer;

Best regards

**Comment by synopse** [comment]
Please try with a more recent version of mORMot.

I already fixed that a few weeks ago, if I remember correctly.

**Comment by synopse** [comment]
I guess it is fixed in the main mORMot but not in SynPdf.
