### ISSUE TITLE
TGDIPages.AppendRichEdit get stack

### ISSUE THREAD

**Issue by limelect** [synopse/SynPDF#54]
TGDIPages.AppendRichEdit( get stack  on
       LastChar := SendMessage(RichEditHandle, EM_FORMATRANGE, 1, Integer(@Range));
dose not move to next char. stay on 13704
loading testrtf.rtf
Using D10.2.3

**Comment by synopse** [comment]
On Win64 I guess?

**Comment by synopse** [comment]
Please try with https://github.com/synopse/SynPDF/commit/4fedae61d575cce21eaa42e60384a807723a4a3b

**Comment by limelect** [comment]
Down loaded last ver
Same problem

**Comment by synopse** [comment]
sqlite3pages.pas is outdated
The new unit is named mormotreport.pas

**Comment by limelect** [comment]
Thanks. can I have a demo link on how to use AppendRichEdit?
As a matter of facts a new pdfrichedit demo

**Comment by limelect** [comment]
OK it workes Thanks
