### ISSUE TITLE
Text with spaces before

### ISSUE THREAD

**Issue by Newgap** [synopse/SynPDF#59]
When printing text containing spaces before it, the alignment is screwed.
We use a fixed width font to maintain column alignment, but when there is space before the text the spaces are not the same width than the font.

**What it should have looked like**
![image](https://user-images.githubusercontent.com/24608259/171488999-06d0207e-dce8-46b8-ad84-4556b43d68c2.png)

**What it looks in the PDF**
![image](https://user-images.githubusercontent.com/24608259/171489025-995f78e5-caed-4ee3-bcca-722ed92c22c3.png)

[Sample.emf.zip](https://github.com/synopse/SynPDF/files/8818399/Sample.zip)

**Comment by synopse** [comment]
What did you try about the UseMetaFileTextPositioning property?

**Comment by Newgap** [comment]
Sweet! it works.
For those wondering where to set that setting, it one of the parameters of the function TPdfDocument.RenderMetaFile()

Thanks again
