### ISSUE TITLE
not found SynFPCMetaFile, 

### ISSUE THREAD

**Issue by RobertoSobreira01** [synopse/SynPDF#66]
I can't find the SynFPCMetaFile.pas unit - how to solve it?

**Comment by synopse** [comment]
There is no FPC compatiblity with SynPDF 1.
You can find this file in https://github.com/synopse/mORMot
But it won't work on FPC.

The version in https://github.com/synopse/mORMot2 has better FPC support, but it is not fully tested nor validated yet.
