### ISSUE TITLE
How to add latex or mathml content?

### ISSUE THREAD

**Issue by luwei0711** [synopse/SynPDF#74]
How to add latex or mathml content?
mathematical formula

**Comment by synopse** [comment]
If you can get the latex or mathml as EMF/WMF, you can append it as a vectorial picture.
Or you need to get the latex or mathml as gif/png and append it as a bitmap picture.

**Comment by luwei0711** [comment]
I see that the formula in the generated PDF can be copied, so it is not using an image, is it?
Even if it's saved in binary, is there an example? Thank you very much!

**Comment by luwei0711** [comment]
> I see that the formula in the generated PDF can be copied, so it is not using an image, is it?
> Even if it's saved in binary, is there an example? Thank you very much!

I see that the formula in the generated PDF can be copied, so it is not using an image, is it?
Even if it's saved in binary, is there an example? Thank you very much!

**Comment by luwei0711** [comment]
> If you can get the latex or mathml as EMF/WMF, you can append it as a vectorial picture. Or you need to get the latex or mathml as gif/png and append it as a bitmap picture.

I see that the formula in the generated PDF can be copied, so it is not using an image, is it?
Even if it's saved in binary, is there an example? Thank you very much!

**Comment by luwei0711** [comment]
Typora already supports the latex formula，Of course, it is based on Chrome and HTML5

**Comment by synopse** [comment]
Did you at least look at the samples provided?
There are samples with pictures.

**Comment by luwei0711** [comment]
> Did you at least look at the samples provided?
> There are samples with pictures.

没有看懂，我是在想，是否有一种可能，把latex公式或mathml公式能够直接写入到pdf文件，用stream？不知道是否可行，大佬是否可以研究一下。谢谢！
