### ISSUE TITLE
Bullet not being correctly represented in PDF

### ISSUE THREAD

**Issue by FernandoSchuch** [synopse/SynPDF#9]
Hi, Synopse!

I've just downloaded the version 1.18 of SynPDF. Thank you very much for keeping your project updated. However, it's not working when I try to export a document with a bullet point in it. Instead of printing the bullet point, it's printing a block/square. Something like this: "[] test".

Is there something i have to set up in the create of TPdfFontTrueType? Does it have to be Unicode or doesn't matter?

Please, see attachment.
[testBullet.pdf](https://github.com/synopse/SynPDF/files/245809/testBullet.pdf)
 I'm using Delphi XE2 with Fortes Report.

**Comment by synopse** [comment]
The best place to discuss is on our forum.
See http://synopse.info/forum/viewforum.php?id=1

Is it related to http://synopse.info/forum/viewtopic.php?id=2365 ?

Arnaud

**Comment by FernandoSchuch** [comment]
Ok, i'll keep that in mind.

Yeah, it is! The following code copied from this link worked for me:

`LDocument.EmbeddedTTF := True;
 LDocument.EmbeddedWholeTTF := True;`

Thanks for your response!
